name: Container Build using Buildah
on:
  push:
permissions:
  contents: read
  packages: write
env:
  IMAGE_NAME: website
  IMAGE_REGISTRY: ghcr.io/queercrew
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set image tags
        id: tag
        run: |
          SAFE_REF_NAME="${GITHUB_REF_NAME//\//-}"

          TAGS="${GITHUB_SHA} ${SAFE_REF_NAME}"
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            TAGS="latest ${TAGS}"
          fi
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        id: build_image
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.tag.outputs.tags }}
          containerfiles: |
            ./Containerfile
          oci: true
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
